Return non-zero value if workflow action fails

diff --git a/.github/workflows/eoepca-aqbb-notebooks-testing.yml b/.github/workflows/eoepca-aqbb-notebooks-testing.yml
--- a/.github/workflows/eoepca-aqbb-notebooks-testing.yml
+++ b/.github/workflows/eoepca-aqbb-notebooks-testing.yml
@@ -13,30 +13,37 @@ jobs:
           PASSWORD: ${{ secrets.EOEPCA_APPLICATION_QUALITY_PASSWORD }}
           PIPELINE_ID: ${{ vars.EOEPCA_APPLICATION_QUALITY_PIPELINE_ID_NOTEBOOKS_STATIC }}
           API_URL: ${{ vars.EOEPCA_APPLICATION_QUALITY_API }}
-          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
         run: |
           # This script allows verifying that the inputs are valid: user credentials, pipeline ID, API URL
           echo "User name: $USERNAME"
           echo "Pipeline ID: $PIPELINE_ID"
           echo "API URL: $API_URL"
-          echo "Branch name: $BRANCH_NAME"
           
+          # Retrieve an access token
           RES_JSON=`curl --json "{ \"username\": \"$USERNAME\", \"password\": \"$PASSWORD\" }" $API_URL/token/`
-          # TODO: Fail if something goes wrong
           ACCESS_TOKEN=`echo $RES_JSON | jq -r '.access'`
-          REFRESH_TOKEN=`echo $RES_JSON | jq -r '.refresh'`
-          echo "Access token: $ACCESS_TOKEN"
-          echo "Refresh token: $REFRESH_TOKEN"
+          if [ "$ACCESS_TOKEN" = "null" ]; then
+            echo "Could not obtain an access token: $RES_JSON"
+            exit 1
+          fi
 
           echo "Pipeline request URL $API_URL/pipelines/$PIPELINE_ID/"
-          curl -H "Authorization: Bearer $ACCESS_TOKEN" $API_URL/pipelines/$PIPELINE_ID/
-          # TODO: Fail if something goes wrong
+          RES_JSON=`curl -H "Authorization: Bearer $ACCESS_TOKEN" $API_URL/pipelines/$PIPELINE_ID/`
+          PIPELINE_ID2=`echo $RES_JSON | jq -r '.id'`
+          PIPELINE_NAME=`echo $RES_JSON | jq -r '.name'`
+          echo "Pipeline ID: $PIPELINE_ID2"
+          echo "Pipeline name: $PIPELINE_NAME"
+          if [ "$PIPELINE_NAME" = "null" ]; then
+            echo "Could not obtain pipeline details: $RES_JSON"
+            exit 2
+          fi
+
   notebooks-static-tests:
     name: Notebooks static tests
     needs: workflow-init
     runs-on: ubuntu-latest
     steps:
-      - name: Retrieve pipeline details
+      - name: Static analysis
         env:
           USERNAME: ${{ vars.EOEPCA_APPLICATION_QUALITY_USERNAME }}
           PASSWORD: ${{ secrets.EOEPCA_APPLICATION_QUALITY_PASSWORD }}
@@ -49,8 +56,11 @@ jobs:
 
           # Retrieve an access token
           RES_JSON=`curl --json "{ \"username\": \"$USERNAME\", \"password\": \"$PASSWORD\" }" $API_URL/token/`
-          # TODO: Fail if something goes wrong
           ACCESS_TOKEN=`echo $RES_JSON | jq -r '.access'`
+          if [ "$ACCESS_TOKEN" = "null" ]; then
+            echo "Could not obtain an access token: $RES_JSON"
+            exit 1
+          fi
 
           REPO_URL="${{ github.server_url}}/${{ github.repository }}"
           REPO_BRANCH="${{ github.head_ref || github.ref_name }}"
@@ -71,7 +81,15 @@ jobs:
             }'
           )
           echo "Execution request payload: $JSON_DATA"
-          curl -H "Authorization: Bearer $ACCESS_TOKEN" --json "$JSON_DATA" $API_URL/pipelines/$PIPELINE_ID/runs/
+          RES_JSON=`curl -H "Authorization: Bearer $ACCESS_TOKEN" --json "$JSON_DATA" $API_URL/pipelines/$PIPELINE_ID/runs/`
+          RUN_ID=`echo $RES_JSON | jq -r '.id'`
+          START_TIME=`echo $RES_JSON | jq -r '.start_time'`
+          echo "Pipeline run ID: $RUN_ID"
+          echo "Start time: $START_TIME"
+          if [ "$RUN_ID" = "null" ]; then
+            echo "Could not execute the pipeline: $RES_JSON"
+            exit 3
+          fi
 
   #notebooks-execution-tests:
   #  name: Notebooks execution tests
